[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'janko-m/vim-test'
on_ft = ['ruby', 'javascript']

[[plugins]]
repo = 'romanvbabenko/rails.vim'
on_ft = ['ruby']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['typescript', 'javascript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'lambdatoast/elm.vim'
on_ft = ['elm']

[[plugins]]
repo = 'vim-scripts/SQLUtilities'
on_map = ['<Plug>SQLUFormatter<CR>']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
'''

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#depends = 'context_filetype.vim'
#on_i = 1
#hook_source = '''
#let g:deoplete#enable_at_startup = 1
#'''

#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#depends = ['context_filetype.vim']
#on_event = 'InsertCharPre'
#on_ft = 'snippet'

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#depends = ['neosnippet.vim']

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#depends = 'deoplete.nvim'
#on_ft = ['rust']
#build = './install.sh'
#hook_source = '''
#let g:LanguageClient_serverCommands = {
#    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
#    \ }
#let g:LanguageClient_autoStart = 1
#nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
#nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
#nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
#'''

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'
on_ft = ['toml', 'markdown']

[[plugins]] # カーソル位置のコンテキストに合わせã¦ftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['toml', 'markdown']
